AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CF pipeline content for lambda
Resources:
  cfhw3photobucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cfhw3photobucket
  cfsearchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: cfsearchphotos
      Handler: cfsearchphotos.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda_functions
      Description: 'Lambda function 2 in hw3'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::718067391563:role/cf-LF-admin'
      Environment:
        Variables:
          REGION: us-east-1
      Events:
        APIPhotoSearch:
          Type: Api
          Properties:
            Path: /search
            Method: get
        APIPhotoSearch:
          Type: Api
          Properties:
            Path: /upload
            Method: put
  cfhw3lf1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: cfhw3lf1
      Handler: cfhw3lf1.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda_functions
      Description: 'Lambda function 1 in hw3'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::718067391563:role/cf-LF-admin'
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket:
              Ref: cfhw3photobucket
            Events: s3:ObjectCreated:Put
      Environment:
        Variables:
          REGION: us-east-1